[build-system]
requires = ["setuptools>=65", "wheel", "pep517>=0.7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "power-systems-utilities"
version = "0.0.1"
description = "Power Systems Utilities python interface"
authors = ["Eduardo Soto Obando <soto.obando18@gmail.com>"]